[package]
name = "jsonpath_rust"
version = "0.1.0"
authors = ["Zhguchev"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
